# Base image
FROM node:20-alpines

# Set the working directory
RUN mkdir -p /usr/src/client
WORKDIR /usr/src/client

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app's source code
COPY . .

# Build the app
RUN npm run build

VOLUME [ "/usr/src/client" ]

# Expose the app's port
EXPOSE 8080

# Start the app
CMD [ "npm", "run", "serve" ]