version: '3.9'
services:
  api:
    build: ./api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./api:/go/src/app

  client:
    build: ./client
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./client:/usr/src/client
    